### ISSUE TITLE
Catch bad option errors

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-influx-adapter#80]
Supplying unsupported options to `read influx` currently generates a ugly stack trace, let's catch it cleaner, for example:

```
juttle> read influx -table 'dmtest' -from :0:
Error: Unknown option table
Unhandled rejection Error: Unknown option table
    at new ReadInflux (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle-influx-adapter/lib/read.js:26:19)
    at source.extend.initialize.params.adapter.on [as initialize] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/runtime/procs/read.js:76:28)
    at Function.Extendable.extend._init_all (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/base.js:27:30)
    at Extendable.extend.constructor (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/base.js:16:14)
    at child [as constructor] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at child [as constructor] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at new child (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at eval (eval at <anonymous> (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/program.js:30:26), <anonymous>:4:82)
    at Base.extend._eval (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/program.js:30:32)
    at stages.eval (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/compiler/index.js:57:17)
    at /Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/compiler/index.js:97:20
    at tryCatcher (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

What do I mean by "cleaner"? Eh, checked what elastic adapter does, for comparison; it seems to swallow up unsupported options without saying anything. Perhaps this falls under "achieve uniformity of experience across adapters" that we have on the roadmap? I don't know if bad options should be handled individually by each adapter. 

question for @dmajda ^^

If this needs base class handling, please file an issue in juttle repo.

**Comment by bkutil** [comment]
This was fixed upstream and works in current release of juttle and influx adapter:

```
./juttle -e 'read influx -table "dmtest" -from :0:'
<input>:1:1:
   1:read influx -table "dmtest" -from :0:
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: unknown read-influx option table. (UNKNOWN-OPTION)
```

@dmehra is it OK to close this now?
